name: "Hello"

on:
  pull_request:
    types: [opened, unopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs review"
